import type { CarteiraClient } from "./types";

const carteiraClientsBase: Array<
  Omit<
    CarteiraClient,
    | "situacaoFinanceira"
    | "observacaoFinanceira"
    | "situacaoCarteira"
    | "observacaoCarteira"
  >
> = [
  {
    id: "cli-001",
    nivel: "saudavel",
    cliente: "Studio Ana Paiva",
    nomeFantasia: "Ana Paiva Hair",
    telefone: "(41) 99912-1840",
    cidade: "Curitiba",
    bairro: "Batel",
    diasSemComprar: 18,
    proximaCompra: "2026-06-05",
    ultimoPedido: "2026-05-08",
    valorUltimoPedido: 1280,
    vendedor: "Camila",
    status: "contatado",
    ultimaAcao: { tipo: "Ligacao realizada", data: "2026-05-23" },
  },
  {
    id: "cli-002",
    nivel: "atencao",
    cliente: "Bella Forma Cosmeticos",
    nomeFantasia: "Bella Forma",
    telefone: "(41) 98877-4201",
    cidade: "Curitiba",
    bairro: "Agua Verde",
    diasSemComprar: 47,
    proximaCompra: "2026-05-24",
    ultimoPedido: "2026-04-09",
    valorUltimoPedido: 742,
    vendedor: "Marcos",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-003",
    nivel: "risco",
    cliente: "Salao Prime Blond",
    nomeFantasia: "Prime Blond",
    telefone: "(41) 99721-1109",
    cidade: "Sao Jose dos Pinhais",
    bairro: "Centro",
    diasSemComprar: 82,
    proximaCompra: "2026-05-20",
    ultimoPedido: "2026-03-05",
    valorUltimoPedido: 1590,
    vendedor: "Renata",
    status: "aguardando",
    ultimaAcao: { tipo: "WhatsApp enviado", data: "2026-05-21" },
  },
  {
    id: "cli-004",
    nivel: "inativo",
    cliente: "Espaco Diva Hair",
    telefone: "(41) 98431-2098",
    cidade: "Colombo",
    bairro: "Maracana",
    diasSemComprar: 174,
    proximaCompra: null,
    ultimoPedido: "2025-12-03",
    valorUltimoPedido: 430,
    vendedor: "Camila",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-005",
    nivel: "saudavel",
    cliente: "Lumiere Centro Estetico",
    telefone: "(41) 99504-8842",
    cidade: "Pinhais",
    bairro: "Vargem Grande",
    diasSemComprar: 26,
    proximaCompra: "2026-06-12",
    ultimoPedido: "2026-04-30",
    valorUltimoPedido: 980,
    vendedor: "Julia",
    status: "convertido",
    ultimaAcao: { tipo: "Pedido recuperado", data: "2026-05-25" },
  },
  {
    id: "cli-006",
    nivel: "atencao",
    cliente: "Maison Beauty Care",
    telefone: "(41) 99640-7302",
    cidade: "Curitiba",
    bairro: "Cabral",
    diasSemComprar: 54,
    proximaCompra: "2026-05-28",
    ultimoPedido: "2026-04-02",
    valorUltimoPedido: 1214,
    vendedor: "Renata",
    status: "visita",
    ultimaAcao: { tipo: "Visita enviada para agenda", data: "2026-05-24" },
  },
  {
    id: "cli-007",
    nivel: "risco",
    cliente: "Ritual dos Cachos",
    telefone: "(41) 99218-5543",
    cidade: "Almirante Tamandare",
    bairro: "Cachoeira",
    diasSemComprar: 91,
    proximaCompra: "2026-05-19",
    ultimoPedido: "2026-02-24",
    valorUltimoPedido: 665,
    vendedor: "Marcos",
    status: "contatado",
    ultimaAcao: { tipo: "Ligacao sem retorno", data: "2026-05-22" },
  },
  {
    id: "cli-008",
    nivel: "inativo",
    cliente: "Flor de Lis Profissional",
    telefone: "(41) 98765-0132",
    cidade: "Curitiba",
    bairro: "Boqueirao",
    diasSemComprar: 218,
    proximaCompra: null,
    ultimoPedido: "2025-10-20",
    valorUltimoPedido: 512,
    vendedor: "Julia",
    status: "aguardando",
    ultimaAcao: { tipo: "Retorno combinado", data: "2026-05-20" },
  },
  {
    id: "cli-009",
    nivel: "saudavel",
    cliente: "Nobre Estetica Avancada",
    telefone: "(41) 99811-4002",
    cidade: "Curitiba",
    bairro: "Merces",
    diasSemComprar: 12,
    proximaCompra: "2026-06-01",
    ultimoPedido: "2026-05-14",
    valorUltimoPedido: 2118,
    vendedor: "Camila",
    status: "convertido",
    ultimaAcao: { tipo: "Pedido confirmado", data: "2026-05-25" },
  },
  {
    id: "cli-010",
    nivel: "atencao",
    cliente: "Beleza Plena Hair",
    telefone: "(41) 99133-8710",
    cidade: "Araucaria",
    bairro: "Centro",
    diasSemComprar: 44,
    proximaCompra: "2026-05-31",
    ultimoPedido: "2026-04-12",
    valorUltimoPedido: 790,
    vendedor: "Sofia",
    status: "contatado",
    ultimaAcao: { tipo: "Mensagem respondida", data: "2026-05-23" },
  },
  {
    id: "cli-011",
    nivel: "risco",
    cliente: "Dona Cor Studio",
    telefone: "(41) 98930-4421",
    cidade: "Fazenda Rio Grande",
    bairro: "Pioneiros",
    diasSemComprar: 77,
    proximaCompra: "2026-05-27",
    ultimoPedido: "2026-03-10",
    valorUltimoPedido: 355,
    vendedor: "Marcos",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-012",
    nivel: "saudavel",
    cliente: "Aquarela dos Fios",
    telefone: "(41) 99772-0065",
    cidade: "Curitiba",
    bairro: "Portao",
    diasSemComprar: 29,
    proximaCompra: "2026-06-08",
    ultimoPedido: "2026-04-27",
    valorUltimoPedido: 1042,
    vendedor: "Renata",
    status: "aguardando",
    ultimaAcao: { tipo: "Follow-up agendado", data: "2026-05-24" },
  },
  {
    id: "cli-013",
    nivel: "inativo",
    cliente: "Studio Mais Vaidosa",
    telefone: "(41) 98518-9205",
    cidade: "Campo Largo",
    bairro: "Vila Bancaria",
    diasSemComprar: 132,
    proximaCompra: "2026-05-22",
    ultimoPedido: "2026-01-14",
    valorUltimoPedido: 612,
    vendedor: "Sofia",
    status: "contatado",
    ultimaAcao: { tipo: "WhatsApp enviado", data: "2026-05-21" },
  },
  {
    id: "cli-014",
    nivel: "atencao",
    cliente: "Elegance Pro Hair",
    telefone: "(41) 99687-7788",
    cidade: "Curitiba",
    bairro: "Santa Felicidade",
    diasSemComprar: 59,
    proximaCompra: "2026-05-26",
    ultimoPedido: "2026-03-28",
    valorUltimoPedido: 899,
    vendedor: "Julia",
    status: "visita",
    ultimaAcao: { tipo: "Visita encaminhada", data: "2026-05-25" },
  },
  {
    id: "cli-015",
    nivel: "risco",
    cliente: "Cachos & Cores Ltda",
    telefone: "(41) 99967-3212",
    cidade: "Pinhais",
    bairro: "Centro",
    diasSemComprar: 68,
    proximaCompra: "2026-05-21",
    ultimoPedido: "2026-03-19",
    valorUltimoPedido: 1478,
    vendedor: "Camila",
    status: "aguardando",
    ultimaAcao: { tipo: "Aguardando decisao", data: "2026-05-22" },
  },
  {
    id: "cli-016",
    nivel: "saudavel",
    cliente: "Lolla Concept Hair",
    telefone: "(41) 99206-5017",
    cidade: "Curitiba",
    bairro: "Bigorrilho",
    diasSemComprar: 8,
    proximaCompra: "2026-06-15",
    ultimoPedido: "2026-05-18",
    valorUltimoPedido: 2305,
    vendedor: "Renata",
    status: "convertido",
    ultimaAcao: { tipo: "Pedido fechado", data: "2026-05-25" },
  },
  {
    id: "cli-017",
    nivel: "inativo",
    cliente: "Nova Essencia Salao",
    telefone: "(41) 98422-1170",
    cidade: "Colombo",
    bairro: "Guaraituba",
    diasSemComprar: 301,
    proximaCompra: null,
    ultimoPedido: "2025-07-29",
    valorUltimoPedido: 285,
    vendedor: "Marcos",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-018",
    nivel: "atencao",
    cliente: "Espaco Urban Beauty",
    telefone: "(41) 99100-6303",
    cidade: "Curitiba",
    bairro: "Cristo Rei",
    diasSemComprar: 39,
    proximaCompra: "2026-06-02",
    ultimoPedido: "2026-04-17",
    valorUltimoPedido: 1186,
    vendedor: "Sofia",
    status: "contatado",
    ultimaAcao: { tipo: "Orcamento enviado", data: "2026-05-22" },
  },
  {
    id: "cli-019",
    nivel: "risco",
    cliente: "Atelie dos Loiros",
    telefone: "(41) 98812-7360",
    cidade: "Curitiba",
    bairro: "Hauer",
    diasSemComprar: 86,
    proximaCompra: "2026-05-23",
    ultimoPedido: "2026-03-01",
    valorUltimoPedido: 940,
    vendedor: "Julia",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-020",
    nivel: "saudavel",
    cliente: "Marina Hair Premium",
    telefone: "(41) 99712-1088",
    cidade: "Sao Jose dos Pinhais",
    bairro: "Afonso Pena",
    diasSemComprar: 31,
    proximaCompra: "2026-06-06",
    ultimoPedido: "2026-04-25",
    valorUltimoPedido: 1388,
    vendedor: "Camila",
    status: "aguardando",
    ultimaAcao: { tipo: "Retorno para sexta", data: "2026-05-24" },
  },
  {
    id: "cli-021",
    nivel: "inativo",
    cliente: "Espaco Fio Nobre",
    telefone: "(41) 98509-4422",
    cidade: "Pinhais",
    bairro: "Weissopolis",
    diasSemComprar: 155,
    proximaCompra: "2026-05-18",
    ultimoPedido: "2025-12-22",
    valorUltimoPedido: 704,
    vendedor: "Renata",
    status: "visita",
    ultimaAcao: { tipo: "Visita encaminhada", data: "2026-05-22" },
  },
  {
    id: "cli-022",
    nivel: "atencao",
    cliente: "Verde Oliva Estetica",
    telefone: "(41) 99621-8904",
    cidade: "Curitiba",
    bairro: "Juveve",
    diasSemComprar: 52,
    proximaCompra: "2026-06-03",
    ultimoPedido: "2026-04-04",
    valorUltimoPedido: 816,
    vendedor: "Marcos",
    status: "convertido",
    ultimaAcao: { tipo: "Pedido recuperado", data: "2026-05-24" },
  },
  {
    id: "cli-023",
    nivel: "risco",
    cliente: "Dama do Corte",
    telefone: "(41) 99998-1200",
    cidade: "Curitiba",
    bairro: "Cajuru",
    diasSemComprar: 73,
    proximaCompra: "2026-05-25",
    ultimoPedido: "2026-03-14",
    valorUltimoPedido: 492,
    vendedor: "Sofia",
    status: "contatado",
    ultimaAcao: { tipo: "Contato sem pedido", data: "2026-05-23" },
  },
  {
    id: "cli-024",
    nivel: "saudavel",
    cliente: "Essential Beauty Bar",
    telefone: "(41) 99172-3377",
    cidade: "Curitiba",
    bairro: "Centro",
    diasSemComprar: 21,
    proximaCompra: "2026-06-10",
    ultimoPedido: "2026-05-05",
    valorUltimoPedido: 1744,
    vendedor: "Julia",
    status: "contatado",
    ultimaAcao: { tipo: "Confirmou recompra", data: "2026-05-25" },
  },
  {
    id: "cli-025",
    nivel: "inativo",
    cliente: "Vitrine da Beleza",
    telefone: "(41) 98488-2214",
    cidade: "Araucaria",
    bairro: "Costeira",
    diasSemComprar: 244,
    proximaCompra: null,
    ultimoPedido: "2025-09-24",
    valorUltimoPedido: 520,
    vendedor: "Camila",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-026",
    nivel: "atencao",
    cliente: "Raiz Forte Cosmeticos",
    telefone: "(41) 99272-5540",
    cidade: "Colombo",
    bairro: "Osasco",
    diasSemComprar: 61,
    proximaCompra: "2026-05-29",
    ultimoPedido: "2026-03-26",
    valorUltimoPedido: 630,
    vendedor: "Renata",
    status: "aguardando",
    ultimaAcao: { tipo: "Aguardando retorno", data: "2026-05-24" },
  },
  {
    id: "cli-027",
    nivel: "risco",
    cliente: "Studio Vila Beauty",
    telefone: "(41) 99780-0021",
    cidade: "Curitiba",
    bairro: "Vista Alegre",
    diasSemComprar: 88,
    proximaCompra: "2026-05-17",
    ultimoPedido: "2026-02-27",
    valorUltimoPedido: 1168,
    vendedor: "Marcos",
    status: "visita",
    ultimaAcao: { tipo: "Visita encaminhada", data: "2026-05-21" },
  },
  {
    id: "cli-028",
    nivel: "saudavel",
    cliente: "Lavanda Hair Spa",
    telefone: "(41) 98890-6409",
    cidade: "Curitiba",
    bairro: "Reboucas",
    diasSemComprar: 34,
    proximaCompra: "2026-06-04",
    ultimoPedido: "2026-04-22",
    valorUltimoPedido: 955,
    vendedor: "Sofia",
    status: "convertido",
    ultimaAcao: { tipo: "Pedido fechado", data: "2026-05-24" },
  },
  {
    id: "cli-029",
    nivel: "inativo",
    cliente: "Perola Negra Studio",
    telefone: "(41) 98670-3110",
    cidade: "Sao Jose dos Pinhais",
    bairro: "Borda do Campo",
    diasSemComprar: 196,
    proximaCompra: "2026-05-16",
    ultimoPedido: "2025-11-11",
    valorUltimoPedido: 384,
    vendedor: "Julia",
    status: "contatado",
    ultimaAcao: { tipo: "Sem interesse no momento", data: "2026-05-20" },
  },
  {
    id: "cli-030",
    nivel: "atencao",
    cliente: "Cristal Pro Salon",
    telefone: "(41) 99580-1774",
    cidade: "Curitiba",
    bairro: "Alto da XV",
    diasSemComprar: 43,
    proximaCompra: "2026-05-30",
    ultimoPedido: "2026-04-13",
    valorUltimoPedido: 846,
    vendedor: "Camila",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-031",
    nivel: "risco",
    cliente: "Top Fios Distribuidora",
    telefone: "(41) 99155-7011",
    cidade: "Piraquara",
    bairro: "Centro",
    diasSemComprar: 95,
    proximaCompra: "2026-05-15",
    ultimoPedido: "2026-02-20",
    valorUltimoPedido: 1892,
    vendedor: "Renata",
    status: "aguardando",
    ultimaAcao: { tipo: "Retorno pendente", data: "2026-05-22" },
  },
  {
    id: "cli-032",
    nivel: "saudavel",
    cliente: "Charm Beauty Lounge",
    telefone: "(41) 99876-2245",
    cidade: "Curitiba",
    bairro: "Mossungue",
    diasSemComprar: 16,
    proximaCompra: "2026-06-09",
    ultimoPedido: "2026-05-10",
    valorUltimoPedido: 1366,
    vendedor: "Marcos",
    status: "contatado",
    ultimaAcao: { tipo: "Mensagem enviada", data: "2026-05-25" },
  },
  {
    id: "cli-033",
    nivel: "inativo",
    cliente: "Doce Beleza Salao",
    telefone: "(41) 98740-6431",
    cidade: "Curitiba",
    bairro: "Sitio Cercado",
    diasSemComprar: 356,
    proximaCompra: null,
    ultimoPedido: "2025-06-04",
    valorUltimoPedido: 275,
    vendedor: "Sofia",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-034",
    nivel: "atencao",
    cliente: "Efeito Gloss Professional",
    telefone: "(41) 99660-8812",
    cidade: "Pinhais",
    bairro: "Atuba",
    diasSemComprar: 57,
    proximaCompra: "2026-06-01",
    ultimoPedido: "2026-03-30",
    valorUltimoPedido: 1075,
    vendedor: "Julia",
    status: "convertido",
    ultimaAcao: { tipo: "Pedido recuperado", data: "2026-05-25" },
  },
  {
    id: "cli-035",
    nivel: "risco",
    cliente: "Mundo dos Cachos",
    telefone: "(41) 98833-0299",
    cidade: "Colombo",
    bairro: "Jardim Eucaliptos",
    diasSemComprar: 79,
    proximaCompra: "2026-05-21",
    ultimoPedido: "2026-03-08",
    valorUltimoPedido: 698,
    vendedor: "Camila",
    status: "contatado",
    ultimaAcao: { tipo: "Cliente pediu retorno", data: "2026-05-22" },
  },
  {
    id: "cli-036",
    nivel: "saudavel",
    cliente: "Blush & Co Estetica",
    telefone: "(41) 99220-1404",
    cidade: "Curitiba",
    bairro: "Bacacheri",
    diasSemComprar: 24,
    proximaCompra: "2026-06-07",
    ultimoPedido: "2026-05-02",
    valorUltimoPedido: 1502,
    vendedor: "Renata",
    status: "aguardando",
    ultimaAcao: { tipo: "Aguardando lista", data: "2026-05-24" },
  },
  {
    id: "cli-037",
    nivel: "inativo",
    cliente: "Natural Line Hair",
    telefone: "(41) 98544-9811",
    cidade: "Campo Magro",
    bairro: "Boa Vista",
    diasSemComprar: 165,
    proximaCompra: "2026-05-18",
    ultimoPedido: "2025-12-12",
    valorUltimoPedido: 460,
    vendedor: "Marcos",
    status: "visita",
    ultimaAcao: { tipo: "Visita encaminhada", data: "2026-05-23" },
  },
  {
    id: "cli-038",
    nivel: "atencao",
    cliente: "Pro Style Curitiba",
    telefone: "(41) 99904-6123",
    cidade: "Curitiba",
    bairro: "Seminario",
    diasSemComprar: 49,
    proximaCompra: "2026-05-27",
    ultimoPedido: "2026-04-07",
    valorUltimoPedido: 1210,
    vendedor: "Sofia",
    status: "nao_trabalhado",
    ultimaAcao: { tipo: "Sem acao registrada", data: null },
  },
  {
    id: "cli-039",
    nivel: "risco",
    cliente: "Casa da Coloracao",
    telefone: "(41) 99770-8834",
    cidade: "Curitiba",
    bairro: "Pinheirinho",
    diasSemComprar: 101,
    proximaCompra: "2026-05-14",
    ultimoPedido: "2026-02-14",
    valorUltimoPedido: 775,
    vendedor: "Julia",
    status: "aguardando",
    ultimaAcao: { tipo: "Aguardando aprovacao", data: "2026-05-21" },
  },
  {
    id: "cli-040",
    nivel: "saudavel",
    cliente: "Espaco Vitoria Hair",
    telefone: "(41) 98414-7750",
    cidade: "Curitiba",
    bairro: "Tingui",
    diasSemComprar: 27,
    proximaCompra: "2026-06-11",
    ultimoPedido: "2026-04-29",
    valorUltimoPedido: 840,
    vendedor: "Camila",
    status: "convertido",
    ultimaAcao: { tipo: "Pedido fechado", data: "2026-05-24" },
  },
  {
    id: "cli-041",
    nivel: "inativo",
    cliente: "Espelho Meu Studio",
    telefone: "(41) 98621-5072",
    cidade: "Almirante Tamandare",
    bairro: "Tanguá",
    diasSemComprar: 277,
    proximaCompra: null,
    ultimoPedido: "2025-08-22",
    valorUltimoPedido: 338,
    vendedor: "Renata",
    status: "contatado",
    ultimaAcao: { tipo: "Telefone atualizado", data: "2026-05-23" },
  },
  {
    id: "cli-042",
    nivel: "atencao",
    cliente: "Duo Hair Professional",
    telefone: "(41) 99117-5908",
    cidade: "Sao Jose dos Pinhais",
    bairro: "Boneca do Iguaçu",
    diasSemComprar: 63,
    proximaCompra: "2026-05-25",
    ultimoPedido: "2026-03-24",
    valorUltimoPedido: 990,
    vendedor: "Marcos",
    status: "visita",
    ultimaAcao: { tipo: "Visita encaminhada", data: "2026-05-25" },
  },
];

const mockFinancialStatusById: Record<
  string,
  Pick<CarteiraClient, "situacaoFinanceira" | "observacaoFinanceira">
> = {
  "cli-003": {
    situacaoFinanceira: "inadimplente",
    observacaoFinanceira:
      "Pendência financeira aberta. Consultar financeiro antes da negociação.",
  },
  "cli-004": {
    situacaoFinanceira: "bloqueado",
    observacaoFinanceira:
      "Cliente bloqueado para novos pedidos até regularização.",
  },
  "cli-011": {
    situacaoFinanceira: "negociacao",
    observacaoFinanceira: "Negociação financeira em andamento.",
  },
};

export const carteiraClients: CarteiraClient[] = carteiraClientsBase.map(
  (client) => ({
    ...client,
    situacaoFinanceira:
      mockFinancialStatusById[client.id]?.situacaoFinanceira ?? "adimplente",
    observacaoFinanceira:
      mockFinancialStatusById[client.id]?.observacaoFinanceira ?? null,
    situacaoCarteira: "ativo",
    observacaoCarteira: null,
  }),
);
